@startuml ERD
entity User {
  * **id number**
  --
  email string
  password string
  fullName string
  * roleId number  <<FK>>
}

entity Vehicle {
  * **id number**
  --
  make string
  vehicle_type car | motorcycle
  model string
  plate_number string
}

entity HouseResident {
  * **id number**
  --
  * house_id number <<FK>>
  * user_id number <<FK>>
}

entity HouseVehicle {
  * **id number**
  --
  * house_id number <<FK>>
  * vehicle_id number <<FK>>
}

entity House {
  * **id number**
  --
  code string
  street string
}

entity Role {
  * **id number**
  --
  name string
}

entity Permission {
  * **id number**
  --
  name string
}

entity RolePermission {
  * **id number**
  --
  * roleId number <<FK>>
  * permissionId number <<FK>>
}

entity EventLog {
  * **id number**
  --
  * targetHouseId number <<FK>>
  * reporterId number <<FK>>
  * vehicleId number <<FK>>
  eventTypeId delivery | visiting
  remarks string
  attachments string
  date timestamp
}


Resident ||..|| HouseResident
Vehicle ||..|| HouseVehicle
House ||..|{ HouseVehicle
User ||..o| Resident
User ||..o| Staff
User ||..|{ Role
Role ||..|{ RolePermission
RolePermission ||..|| Permission
HouseResident }|..|| House
House ||..o{ EventLog
User ||..o{ EventLog
Vehicle ||..o{ EventLog


@endumloin